project: MyRecon
name: basic
model:
  target: models.Low2HighNet.Low2HighNet
  params:
    lr: 1e-3
    ch_in: 1
    ch_out: 1
data:
  target: datamodules.DataModule.DataModule
  params:
    config_dataset_train:
      target: datasets.Low2HighMaskDataset.Low2HighMaskDataset
      params:
        path_index: data_index/train_birds_vivid_mask.txt
        size: 256
    config_dataset_valid:
      target: datasets.Low2HighMaskDataset.Low2HighMaskDataset
      params:
        path_index: data_index/valid_birds_vivid_mask.txt
        size: 256
    config_dataloader_train:
      batch_size: 64 
      shuffle: True
      num_workers: 4
      pin_memory: True
    config_dataloader_valid:
      batch_size: 32
      shuffle: False
      num_workers: 4
      pin_memory: True

trainer:
  max_epochs: 200
  precision: 16
  # limit_val_batches: 2
