project: MyRecon
name: basic
model:
  target: models.UNet.UNet
  params:
    lr: 1e-3
    ch_in: 3
    ch_out: 3
data:
  target: datas.BasicData.BasicData
  params:
    path_train: datasets/birds_imagenet/train/
    path_valid: datasets/birds_imagenet/valid/
    size: 256
    config_dataloader_train:
      batch_size: 64 
      shuffle: True
      num_workers: 4
      pin_memory: True
    config_dataloader_valid:
      batch_size: 64
      shuffle: False
      num_workers: 4
      pin_memory: True

trainer:
  max_epochs: 200
  precision: 16
  # limit_val_batches: 2
